cp .gitignore akutagawa_rashomon_lunna
cp .gitignore almeida_antologia_maismelhores
cp .gitignore andrade_antologia_hedraeducacao
cp .gitignore andrade_cronicas
cp .gitignore andrade_eutudoamo
cp .gitignore anonimo_graal_ayllon
cp .gitignore arturazevedo_peledolobo_circuito
cp .gitignore athayde_cordel_hedra
cp .gitignore atui_mare2_n-1_araucaria
cp .gitignore barreto_contos
cp .gitignore baudelaire_pequenos_acorde
cp .gitignore brown_narrativa_relicario
cp .gitignore cardim_tratado-pisagrama2
cp .gitignore defoe_crusoe_ayllon
cp .gitignore dostoievski_subsolo
cp .gitignore firmina_antologia_acorde
cp .gitignore gabrielsoares_tratado_piseagrama
cp .gitignore gama_luta
cp .gitignore gandavo_historia_hedraeducacao
cp .gitignore heine_rabi_iluminuras
cp .gitignore hesiodo_antologia_hedraeducacao
cp .gitignore jacobs_incidentes_n-1_nexus
cp .gitignore joyce_dublinenses_hedraeducacao
cp .gitignore joyce_retrato_hedraeducacao
cp .gitignore joyce_stephen_hedraeducacao
cp .gitignore lobato_contos
cp .gitignore lovecraft_cthulhu_cor
cp .gitignore machado_cartomante_piseagrama
cp .gitignore machado_paicontramae_lamparina
cp .gitignore Makefile
cp .gitignore marra_crack_beatrizME
cp .gitignore menezes_jazzrural_hedraeducacao
cp .gitignore mi_trans_noite_n-1
cp .gitignore mi_trans_terra_n-1
cp .gitignore panelas_cordel_hedraeducacao
cp .gitignore patativa_cordel_hedraeducacao
cp .gitignore patativa_fulo
cp .gitignore rodolfo_cordel_hedraeducacao
cp .gitignore safo_antologia_renato
cp .gitignore schwob_vidas_cruzada_renato
cp .gitignore stevenson_jekyll_hedraeducacao
cp .gitignore stocker_sol_relicario
cp .gitignore strindberg_hemso_beatrizME
cp .gitignore strindberg_sagas_circuito_blooks
cp .gitignore tieck_feitico_maismelhores
cp .gitignore tolstoi_morte
cp .gitignore twain_diário_edlabpress
cp .gitignore vieira_sermoes_hedraeducacao
cp .gitignore wpa_narrativas_hedra
cp .gitignore xavier_viagem_n-1_araucaria
cp .gitignore zevicente_cordel_hedraeducacao
cp .gitignore zola_acuso
