gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[acorde]{..\/edlab}/' PNLD0010_acorde_baudelairepequenos_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[acorde]{..\/edlab}/' PNLD0014_acorde_firminaantologia_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[andorinhas]{..\/edlab}/' PNLD0003_he_vieirasermoes_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[andorinhas]{..\/edlab}/' PNLD0032_he_joycedublinenses_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[araucaria]{..\/edlab}/' PNLD0008_araucaria_atuimare_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[araucaria]{..\/edlab}/' PNLD0046_araucaria_maistreviagem_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[arlecchino]{..\/edlab}/' PNLD0017_he_stevensonmedico_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[ayllon]{..\/edlab}/' PNLD0006_ayllon_baccegagraal_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[ayllon]{..\/edlab}/' PNLD0013_ayllon_defoerobinson_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[blooks]{..\/edlab}/' PNLD0033_blooks_patativaispinho_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[blooks]{..\/edlab}/' PNLD0040_blooks_strindbergsagas_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[circuito]{..\/edlab}/' PNLD0005_circuito_andradetudoamo_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[circuito]{..\/edlab}/' PNLD0024_circuito_lobatosuplicio_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[edlab]{..\/edlab}/' PNLD0016_edlab_gamaabolicao_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[edlab]{..\/edlab}/' PNLD0043_edlab_twaindiarios_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[escoladepais]{..\/edlab}/' PNLD0035_escola_safohino_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[escoladepais]{..\/edlab}/' PNLD0036_escola_schwobvidas_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[fenix]{..\/edlab}/' PNLD0025_he_vicentecordel_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[fenix]{..\/edlab}/' PNLD0012_he_panelascordel_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[hedra]{..\/edlab}/' PNLD0007_hedra_wpanascidos_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[hedra]{..\/edlab}/' PNLD0045_hedra_athaydecordel_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[iluminuras]{..\/edlab}/' PNLD0018_iluminuras_heinerabi_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[indico]{..\/edlab}/' PNLD0019_he_patativacordel_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[indico]{..\/edlab}/' PNLD0031_he_rodolfocordel_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[kalinka]{..\/edlab}/' PNLD0049_kalinka_tolstoinikita_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[kalinka]{..\/edlab}/' PNLD0050_kalinka_contosrussos_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[lamparina]{..\/edlab}/' PNLD0026_lamparina_machadopai_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[lunna]{..\/edlab}/' PNLD0001_lunna_barretocronicas_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[lunna]{..\/edlab}/' PNLD0009_lunna_akutagawarashomon_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[madalena]{..\/edlab}/' PNLD0004_madalena_andradezeppelin_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[madalena]{..\/edlab}/' PNLD0042_madalena_tolstoiivan_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[magrela]{..\/edlab}/' PNLD0022_he_joycestephen_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[magrela]{..\/edlab}/' PNLD0044_he_hesiodoteogonia_trabalhos_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[maisemelhores]{..\/edlab}/' PNLD0002_mm_almeidacontos_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[maisemelhores]{..\/edlab}/' PNLD0041_mm_tieckfeitico_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[nexus]{..\/edlab}/' PNLD0020_nexus_jacobsincidentes_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[nexus]{..\/edlab}/' PNLD0030_nexus_fontelapoesia_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[nmenosum]{..\/edlab}/' PNLD0029_n-1_ballesteryanomami_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[papagaio]{..\/edlab}/' PNLD0027_glac_marracrack_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[papagaio]{..\/edlab}/' PNLD0039_XXX_strindberghemso_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[piseagrama]{..\/edlab}/' PNLD0015_piseagrama_gabrieltratado_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[piseagrama]{..\/edlab}/' PNLD0048_piseagrama_machadocartomante_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[prosper]{..\/edlab}/' PNLD0023_he_cardimtratado_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[prosper]{..\/edlab}/' PNLD0037_he_joyceretrato_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[relicario]{..\/edlab}/' PNLD0011_relicario_stokersol_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[relicario]{..\/edlab}/' PNLD0038_relicario_brownnarrativa_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[trilhadosaber]{..\/edlab}/' PNLD0034_he_gandavoprovincia_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[tulipa]{..\/edlab}/' PNLD0021_he_lovecraftchulhu_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[youkali]{..\/edlab}/' PNLD0028_he_andradeperu_MIOLO/LIVRO.tex
gsed -i 's/\\usepackage{..\/edlab}/\\usepackage[youkali]{..\/edlab}/' PNLD0047_he_menezesjazz_MIOLO/LIVRO.tex
