all:
	#svn propset svn:keywords "Date Id Rev" *.tex
	pdflatex TOMO1.tex
	evince TOMO1.pdf

dois:
	#svn propset svn:keywords "Date Id Rev" *.tex
	pdflatex TOMO2.tex
	evince TOMO2.pdf

clean:
	rm *.aux *.dvi *.log TOMO[12].pdf *.ps *.toc
