mv ARAUCARIA_LOGO_2.png logoaraucaria.png
mv AYLLON_LOGO_NOMES_CIRCULO.png logoayllon.png
mv CIRCUITO_LOGO_3.png logocircuito.png
mv EDLAB_LOGO_VERMELHO.png logoedlab.png
mv ESCOLA_LOGO_6.png logoescoladepais.png
mv GLAC_LOGO.png logoglac.png
mv HEDRA_LOGO_PRETO.png logohedra.png
mv ILUMINURAS_LOGO.png logoiluminuras.png
mv IMA_LOGO.png logoima.png
mv KALINKA_LOGO.png logokalinka.png
mv logoacorde.png logoacorde.png
mv MAIS_MELHORES_LOGO.png logomaisemelhores.png
mv N-1_LOGO_2.png logonmenosum.png
mv PLANA_LOGO.png logoplana.png
mv RELICARIO_LOGO.png logorelicario.png
mv UBU_LOGO.png logoubu.png
