gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0005-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0010-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0012-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0019-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0025-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0030-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0031-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0033-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0035-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0044-MP.tex
gsed -i '/\\tableofcontents/ r tema_poema.tex' PNLD0045-MP.tex